### ISSUE TITLE
Archives are not shipped

### ISSUE THREAD

**Issue by Gnimuc** [JuliaBinaryWrappers/Clang_jll.jl#1]
`libclang*.a`s are shipped in `LLVM_jll` instead of this package, but this command seems to be correct:
https://github.com/JuliaPackaging/Yggdrasil/blob/68eba607e21718152ea307655ca5c261cd318cca/L/LLVM/common.jl#L276

Also, `libLLVM*.a`s are shipped in both `LLVM_jll` and `libLLVM_jll`.

**Comment by giordano** [comment]
Do you really need the static archives?  Other people don't seem to agree: https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/issues/4.

Unrelated, issues under this organisation are quite unlikely to be seen by anyone, better make this comment to Yggdrasil

**Comment by Gnimuc** [comment]
As far as I can tell, Cxx.jl do need to link to those libs: https://github.com/JuliaInterop/Cxx.jl/pull/465/files#diff-c002a594a18961699f1519658022b71eL82-R87
